/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ContactInfoService } from "../contactInfo.service";
import { ContactInfoCreateInput } from "./ContactInfoCreateInput";
import { ContactInfo } from "./ContactInfo";
import { ContactInfoFindManyArgs } from "./ContactInfoFindManyArgs";
import { ContactInfoWhereUniqueInput } from "./ContactInfoWhereUniqueInput";
import { ContactInfoUpdateInput } from "./ContactInfoUpdateInput";

export class ContactInfoControllerBase {
  constructor(protected readonly service: ContactInfoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContactInfo })
  async createContactInfo(
    @common.Body() data: ContactInfoCreateInput
  ): Promise<ContactInfo> {
    return await this.service.createContactInfo({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ContactInfo] })
  @ApiNestedQuery(ContactInfoFindManyArgs)
  async contactInfos(@common.Req() request: Request): Promise<ContactInfo[]> {
    const args = plainToClass(ContactInfoFindManyArgs, request.query);
    return this.service.contactInfos({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContactInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async contactInfo(
    @common.Param() params: ContactInfoWhereUniqueInput
  ): Promise<ContactInfo | null> {
    const result = await this.service.contactInfo({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContactInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateContactInfo(
    @common.Param() params: ContactInfoWhereUniqueInput,
    @common.Body() data: ContactInfoUpdateInput
  ): Promise<ContactInfo | null> {
    try {
      return await this.service.updateContactInfo({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContactInfo })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteContactInfo(
    @common.Param() params: ContactInfoWhereUniqueInput
  ): Promise<ContactInfo | null> {
    try {
      return await this.service.deleteContactInfo({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
