/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ContactInfo } from "./ContactInfo";
import { ContactInfoCountArgs } from "./ContactInfoCountArgs";
import { ContactInfoFindManyArgs } from "./ContactInfoFindManyArgs";
import { ContactInfoFindUniqueArgs } from "./ContactInfoFindUniqueArgs";
import { DeleteContactInfoArgs } from "./DeleteContactInfoArgs";
import { ContactInfoService } from "../contactInfo.service";
@graphql.Resolver(() => ContactInfo)
export class ContactInfoResolverBase {
  constructor(protected readonly service: ContactInfoService) {}

  async _contactInfosMeta(
    @graphql.Args() args: ContactInfoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ContactInfo])
  async contactInfos(
    @graphql.Args() args: ContactInfoFindManyArgs
  ): Promise<ContactInfo[]> {
    return this.service.contactInfos(args);
  }

  @graphql.Query(() => ContactInfo, { nullable: true })
  async contactInfo(
    @graphql.Args() args: ContactInfoFindUniqueArgs
  ): Promise<ContactInfo | null> {
    const result = await this.service.contactInfo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ContactInfo)
  async deleteContactInfo(
    @graphql.Args() args: DeleteContactInfoArgs
  ): Promise<ContactInfo | null> {
    try {
      return await this.service.deleteContactInfo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
